[LP-7000S]
InstallSettingFile2K = LP7000S.INF

InstallGuide0 = ReadmeCHT.txt
InstallGuide2 = ReadmeEN.txt
HandBook0 = ..\..\Manual\LP-7000S¾Þ§@¤â¥U.pdf
Hint0 = LP-7000S 106¦C¥­±À¦¡¦Lªí¾÷
HandBook = ..\..\Manual\LP-7000S²Ù×÷ÊÖƒÔ.pdf
Hint = LP-7000S 106¦C¥­±À¦¡¦Lªí¾÷
HandBook2 = ..\..\Manual\LP-7000S User's Manual.pdf
Hint2 = LP-7000S Printer

SelectPort = 0
DefaultPortName = USB
ForceOnlineCheck = 0
PromptCheck = 0

InstallDll2K = i386\inst2k.dll
UnInstallImage2K = i386\JMPrnUni.exe
;RegSetImage2000 = i386\Setup32
InstallImage64 = X64\PrnSetup64.exe
InstallDll64 = X64\inst2k64.dll
UnInstallImage64 = 
AutoMode = 0
QuiteMode = 0
PrintProcess = 
